### PR TITLE
Bump version number to 2.0.0

### PR DESCRIPTION
**Pull request by jamoralp**
This PR was created to sync with the upcoming Micro XRCE-DDS 2.0.0 release.

Steps:
* [x] Check integration tests result, and fix if necessary.
* [x] For now, Micro XRCE-DDS Client and Micro XRCE-DDS Agent tags are kept to "develop". When releasing the 2.0.0 version, make sure to change them to `2.0.0`. This involves some previous work regarding the agent and client repositories, as their 2.0.0 tag must be ready before proceeding. Link here the pull requests for the 2.0.0 release of the `Micro XRCE-DDS Agent` and the `Micro XRCE-DDS Client`, when applicable.
* [x] Include some missing integration tests, such as `Client -> Agent Ping`. https://github.com/eProsima/Micro-XRCE-DDS/pull/61
    - [x] ~Review internal documentation about test coverage @jamoralp~
* [x] **Readthedocs**: Review documentation, updating commands and sections where necessary.
     - [x] Check that documentation installation and examples instructions works
* [x] Update dockerfiles, and automate the creation of Docker images in dockerhub platform. Right now, last image of Micro XRCE-DDS general repository, agent and client were uploaded from 4 to 7 months ago.
    * [x] Automatize dockerhub @jamoralp  
* [x] Review the `Micro XRCE-DDS Apps` structure and make it more user friendly.
    * [x] https://github.com/eProsima/Micro-XRCE-DDS-Apps/issues/17 
    * [x] https://github.com/eProsima/Micro-XRCE-DDS-Apps/pull/18
* [x] Decide what to do with Micro XRCE-DDS Gen repository.
    - [x] Check if works: ok (Pablo)
    - [x] Check tests: don't have test (Pablo)
    - [x] Should we update this to v2.0.0 if it does not have changes? We **are not** updating

Related PR that should be merged:
### Client:
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/180
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/179
     - [x] Document new custom transport API: readthedocs
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/178
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/177
     - [ ] Document new continuous fragment API: readthedocs
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/171 <- https://github.com/eProsima/Micro-XRCE-DDS/pull/62
- [x] Keep in develop: https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/164
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/97 <- evaluate close. NOT MERGING
### Agent
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/205
     - [x] Document new custom transport API: readthedocs
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/203
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/193 <- https://github.com/eProsima/Micro-XRCE-DDS/pull/62
- [x] https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/102 <- evaluate close. NOT MERGING REBASE NEEDED
### RMW
- [x] https://github.com/micro-ROS/rmw-microxrcedds/pull/91
- [x] https://github.com/micro-ROS/rmw-microxrcedds/pull/89
- [x] Keep in develop:  https://github.com/micro-ROS/rmw-microxrcedds/pull/76
- [x] Agent ping in RMW @jamoralp -> https://github.com/micro-ROS/rmw-microxrcedds/pull/94

### TODO next sprint:
- [x] Hide `uxr_***_platform` from user API @jamoralp : 
     - [x] https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/183
     - [x] https://github.com/eProsima/Micro-XRCE-DDS/pull/63
     - [x] https://github.com/eProsima/Micro-XRCE-DDS-Apps/pull/19 
- [x] Remove old transport approach: https://github.com/micro-ROS/micro_ros_setup/pull/269
     - Foxy and Galactic with new transport API
     - v2.0.0 XRCE-Client new transport API
         - [x] Update [micro-ROS build](https://github.com/micro-ROS/micro_ros_setup) system with new approach
         - [ ] ~Refactor test to avoid duplications between serial_comm and custom_comm~
         - [x] Remove `RMW_UXRCE_TRANSPORT_CUSTOM_SERIAL` from rmw https://github.com/micro-ROS/rmw-microxrcedds/pull/91
- [ ] **Related but not included in XRCE**: Refactor user RMW API: https://github.com/micro-ROS/rmw-microxrcedds/pull/103
- [x] Jenkins nightly CI

# How to release:
- We are going to merge all these related PR to `develop` and create a new tag named `v2.0.0-r1`
- With ROS2 Galactic we are going to release a `v2.0.0` in master

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/110/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/129/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/111/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/130/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/112/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/131/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/115/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/134/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/123/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/142/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/126/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/145/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/133/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/152/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/134/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/153/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/146/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/165/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/162/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/181/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/165/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/184/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/166/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/185/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/168/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/187/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/169/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/188/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/170/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/189/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/173/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/192/)

**Review by pablogs9 — APPROVED** [review]

**Pull request merged**
